### ISSUE TITLE
Background Dots and Highlighted Objects.

### ISSUE THREAD

**Issue by TobiasWallner** [simulton/QSchematic#66]
As it looks like the default background of a scene has some dots/grid pattern. Is it supposed to not stretch over the whole sceene? 
![image](https://github.com/simulton/QSchematic/assets/70602844/55d41973-f044-41fc-a61c-ecad26361fb5)

---
When I mark / click on an object it gets highlighted, but the highlight never fully disappears. Only a thin border around the object disappears. 
When I click on the object it looks like this:
![image](https://github.com/simulton/QSchematic/assets/70602844/78fe58a6-3415-421b-ba9e-ab539800e528)

When I then unselect it it looks and stays like that:
![image](https://github.com/simulton/QSchematic/assets/70602844/c9b162b7-b82d-428e-bb8e-60d02b27a8ab)

could that be an QT rendering issue?

**Comment by Tectu** [comment]
See #59 

From what I know, the scene only resizes (into the positive direction) when adding items. If the item's bound box extends over the scene rect after moving it, it does not resize further. Whether this is an intentional design decision of the underlying Qt Graphics View Framework or configurable behavior I currently don't recall.
In any case, we want to improve the way the background/grid is being handled anyway as discussed in the mentioned issue.

Try to set `QSchematic::Scene::setSceneRect(0, 0, 1000, 1000);` as a start.
